# Sidebar menu
menu:
  home: /
  about: /about
  life: /life

# Profile
profile:
  avatar: img/avatar.jpg
  # Email address will be used for showing gravatar(https://en.gravatar.com) avatar if `avatar` is not specified.
  email: WincerChan@gmail.com
  bio: Carpe diem.

# Social media
# Try to sort by changing the order of the keys
sns:
  # `email` will fallback to `profile.email` if not specified
  email: WincerChan@gmail.com
  # `feed` will fallback to `feed.path` of site if not specified
  feed: /atom.xml
  github: https://github.com/WincerChan
  telegram: https://t.me/Tivsae
  twitter:
  facebook:
  tumblr:
  instagram:
  dribbble:
  gplus:
  weibo:
  qq:

footer:
  # If not defined, will show current year and author, eg: ©2018 • Superman
  copyright: "&copy; 2017 - 2018 ♥ <a href=\"https://diem.im\">Wincer</a>"

  # Set to false to hide Hexo link.
  powered: true
  # Set to false to hide theme info.
  theme: true

  # Custom text can be defined here.
  # custom: Hosted by <a target="_blank" rel="external nofollow" href="https://pages.coding.me"><b>Coding Pages</b></a>

# Post
post:
  per_page: 8
  # Table of content
  # Set to false to disable
  toc:
    # The depth of toc, default is 2, maximum to 4.
    # depth: 3
    # Showing index before toc, eg. 1.1 title
    index: false

### Pagination size
# The amount of posts displayed on a single archive/tag/category page, default is `10`, set to `0` to disable pagination.
archive:
  per_page: 16
tag:
  per_page: 10
category:
  per_page: 16

# Favicon
# Default is `favicon.ico`
# favicon: favicon.ico

theme:
  # body background image
  background:
  # sidebar background image
  sidebar_background:
  # maximum width of content
  # content_width: 640

# Disqus comments
comments:
  disqus:
    shortname: wincer
    # Set to true to auto load disqus, otherwise will show a button
    autoload: false

# Assets path
assets:
  prefix: 'https://cloudinary.com/console/media_library/folders/all/blog/'
  # suffix: '?m=webp&q=80'

# Web App Manifest
manifest:
  # short_name:
  # name:
  # start_url: /
  # theme_color: '#2a2b33'
  # background_color: '#2a2b33'
  # icons:
  #   - src: icon-194x194.png
  #     sizes: 194x194 512x512
  #     type: image/png
  #   - src: icon-144x144.png
  #     sizes: 144x144
  #     type: image/png

# Google analytics
# ga: UA-00000000-0
